version: '3'
services:
  app:
    build: .
    network_mode: host
    environment:
      project_name: *project_name*
      project_type: vue
    volumes:
      - *path_to_app*/app:/app
    privileged: true
